<?php

?>
<!doctype html>
<html>
<head>
<title>Advanced Development</title>
<link href='style.css'  rel='stylesheet' />

</head>
<body class='home'>


<header>
<nav>

<a href='index.html' id='logo'>
The Best Sushi in Town<br />
Amarillo Tx</a>




<ul>
<li class='design-link'><a href='index.html'>Home</a>
	
</li>
<li class='navigation-link'><a href='menu.html'>Menu</a>

	

</li>
<li class='layout-link'><a href='drinks.html'>Drinks</a>
	
</li>
<li class='tables-link'><a href='contact.html'>Contact</a>
	
</li>

</ul>

<br class='clear' />


</nav>

    </header>
    
</div><!--/inner-->








<section id='overview'>
<div class='inner'>



<div class='section-left'>


        <ul class='wine'>
        <h2>HOUSE WINE </h2>
        <li>Cabernet............... glass 5.00 bottle 17.00 8.00</li>
        <li>Chardonnay .............glass 5.00 bottle 17.00 8.00</li>
        <li>Merlot .................glass 5.00 bottle 17.00 8.00</li>
        <li>White Zinfandel.........glass 5.00 bottle 17.00 8.00</li>
    </ul>
        

</div><!--/left-->

<div class='section-right'>

<ul class='wine'>
        <h2>PREMIUM </h2>
    <li>Kendall Jackson Cabernet........... glass 8.00 bottle 25.00</li>
    <li>kendall Jackson Merlot .............glass 8.00 bottle 25.00</li>
    <li>Kendall Jackson Chardonnay..........glass 8.00 bottle 25.00</li>
    <li>Rosatello Moscato...................glass 8.00 bottle 25.00</li>
    <li>Relax Riesling......................glass 8.00 bottle 25.00</li>
    </ul>
</div><!--/right-->


<br class='clear' />

</div><!--/inner-->





</section>


<section id='design'>
<div class='inner'>


<div class='section-left'>
 <h2>DOMESTICS</h2>
        <li>Bud Light............ 3.00</li>
        <li>Coors Light.......... 3.00</li>
        <li>Budweiser............ 3.00</li>    
        <li>Shiner Bock.......... 3.00</li>
        <li>Miller Light......... 3.00</li>
        <li>Michelob Ultra....... 3.00</li>
        
    

</div><!--/left-->

<div class='section-right'>
<img src='7651043504_IMG_2404.JPG' alt='Design Image' width="350" height="300" />
</div><!--/right-->


<br class='clear' />

</div><!--/inner-->
</section>




    

<footer>
	<div class="inner">
	
	<p >
		The content of this site has been generated by Derek Weathersbee and other members of the Amarillo College staff, and is for educational use only. Inclusion of imagery on this site does not imply creation of the imagery by the site’s creators, and the imagery used remains the intellectual property of the content’s respective creators.
	</p>

	</div>

</footer>


</body>
</html>
