<?php

?>
<!doctype html>
<html>
<head>
<title>Advanced Development</title>
<link href='style.css'  rel='stylesheet' />

</head>
<body class='home'>


<header>
<nav>

<a href='index.html' id='logo'>
The Best Sushi in Town<br />
Amarillo Tx</a>


<ul>
<li class='design-link'><a href='index.html'>Home</a>
	
</li>
<li class='navigation-link'><a href='menu.html'>Menu</a>

	

</li>
<li class='layout-link'><a href='drinks.html'>Drinks</a>
	
</li>
<li class='tables-link'><a href='contact.html'>Contact</a>
	
</li>

</ul>

<br class='clear' />


</nav>

<div class='inner'>



<br class='clear' />

</div><!--/inner-->

</header>






<section id='overview'>
<div class='inner'>


<div class='section-left'>
<h2>Maki Sushi</h2>
        <li>Monkey Balls............ 9.00</li>
        <li>Crunchy Roll.......... 31.00</li>
        <li>Samurai............ 13.00</li>    
        <li>Cat Roll.......... 23.00</li>
        <li>Vocano Roll......... 30.00</li>
        <li>Cucumber Roll....... 31.00</li>
         <li>Canjun............ 9.00</li>
        <li>Sunset Roll.......... 31.00</li>
        <li>Spider Roll............ 13.00</li>    
        <li>Snake Roll.......... 23.00</li>
        <li>Chihuahua Roll......... 30.00</li>
        <li>Tiger Roll....... 31.00</li>

</div><!--/left-->

<div class='section-right'>

<img src='7651043504_IMG_2507.JPG' alt='Froggy' width="350" height="300" class='positioned'>

</div><!--/right-->


<br class='clear' />

</div><!--/inner-->
</section>




<section id='design'>
<div class='inner'>



<div class='section-left'>
<h2>Sashimi</h2>
        <li>Salmon............ 9.00</li>
        <li>White Tuna........ 31.00</li>
        <li>Yellow tail....... 13.00</li>    
        <li>Fatty Tuna........ 23.00</li>
        <li>Vocano Roll....... 30.00</li>
        <li>Cucumber Roll..... 31.00</li>
         <li>Canjun........... 9.00</li>
        <li>Sunset Roll........31.00</li>
        <li>Spider Roll....... 13.00</li>    
        <li>Snake Roll.........23.00</li>
        <li>Chihuahua Roll.....30.00</li>
        <li>Tiger Roll.........31.00</li>


</div><!--/left-->

<div class='section-right'>
    <h2>Hand Roll</h2>
<li>Salmon............ 9.00</li>
        <li>White Tuna........ 31.00</li>
        <li>Yellow tail....... 13.00</li>    
        <li>Fatty Tuna........ 23.00</li>
        <li>Vocano Roll....... 30.00</li>
        <li>Cucumber Roll..... 31.00</li>
         <li>Canjun........... 9.00</li>
        <li>Sunset Roll........31.00</li>
        <li>Spider Roll....... 13.00</li>    
        <li>Snake Roll.........23.00</li>
        <li>Chihuahua Roll.....30.00</li>
        <li>Tiger Roll.........31.00</li>
</div><!--/right-->


<br class='clear' />

</div><!--/inner-->
    
    <div class="slideshow-container">

    

  <div class="mySlides fade">
    <div class="numbertext">1 / 5</div>
    <img src="7651043504_IMG_2508.JPG" style="width:100%">
    <div class="text">Alaskan</div>
  </div>

  <div class="mySlides fade">
    <div class="numbertext">2 / 5</div>
    <img src="7651043504_IMG_2407.JPG" style="width:100%">
    <div class="text">Tiger Tear</div>
  </div>
        
        <div class="mySlides fade">
    <div class="numbertext">3 / 5</div>
    <img src="7651043504_IMG_2409.JPG" style="width:100%">
    <div class="text">Rainbow</div>
  </div>
        
        <div class="mySlides fade">
    <div class="numbertext">4 / 5</div>
    <img src="7651043504_IMG_2503.JPG" style="width:100%">
    <div class="text">Monkey</div>
  </div>
        
       

  
  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>
</div>
<br>



    

    
  
    
<script>
var slideIndex = 0;
showSlides();

function showSlides() {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none"; 
    }
    slideIndex++;
    if (slideIndex > slides.length) {slideIndex = 1} 
    slides[slideIndex-1].style.display = "block"; 
    setTimeout(showSlides, 2000); // Change image every 2 seconds
}
</script>
    
    


    
    

</section>




    

<footer>
	<div class="inner">
	
	<p >
		The content of this site has been generated by Derek Weathersbee and other members of the Amarillo College staff, and is for educational use only. Inclusion of imagery on this site does not imply creation of the imagery by the site’s creators, and the imagery used remains the intellectual property of the content’s respective creators.
	</p>

	</div>

</footer>


</body>
</html>

